### ISSUE TITLE
add dialect study participants

### ISSUE THREAD

**Issue by tjmahr** [LearningToTalk/L2TDatabase#47]
It looks like we were doing a couple of studies under the umbrella of "Dialect". Some children did a `DialectDensity` set of tasks, many more did `DialectSwitch` tasks, and some did both. Thus:

![image](https://cloud.githubusercontent.com/assets/1890315/20944358/c092546e-bbc8-11e6-9d38-5063b7a8d5e1.png)

I'm going to use `Dialect` to cover both. There is one child `402D` who had received DialectDensity testing then 10 months later received a new batch of DialectSwitch and DialectDensity testing. I am going to archive 402D's earlier testing. 

- [x] create studies in Study table
- [x] create entries in Child table
  - Except for the following aliases: 120L = 458D (double-check?)
- [x] create entries in ChildStudy table

**Comment by janroslynedwards** [comment]
Dialect density = Ruby's thesis

Dialect shift = study where children got RWL in both dialects.
