### ISSUE TITLE
add gfta standard to timepoint 3 query

### ISSUE THREAD

**Issue by tjmahr** [LearningToTalk/L2TDatabase#49]
I've added GFTA scores for all of our studies. Now I can integrate them into our study summary queries.

**Comment by janroslynedwards** [comment]
Yay! Do we have them for all studies except time point 2?

**Comment by tjmahr** [comment]
Yep

**Comment by tjmahr** [comment]
done 

![image](https://cloud.githubusercontent.com/assets/1890315/21232533/9860cecc-c2b1-11e6-8ce2-d3dcea1976b8.png)
